### ISSUE TITLE
[Suggestion] Mod command

### ISSUE THREAD

**Issue by Lautenschlager-id** [a801-luadev/parkour#29]
Allow parkour moderators to whisper a bot with a specific command so that a specific room increases the limit of players by 1.

If the room is full, the moderator cannot check reports.

The command would save somewhere that the room X needs to +1 the limit. The rooms would listen to it and when there's a signal they'll increase it temporarily.

**Comment by tocuto** [comment]
I have been tried to implement this, but I couldn't because of a transformice bug. It is in the code, but it doesn't work. Any help would be appreciated

**Comment by Lautenschlager-id** [comment]
Send the PR that it has been added and I'll take a look

**Comment by tocuto** [comment]
Thank you. I guess the problem is that rooms just don't want to execute tfm.exec.setRoomMaxPlayers, yet it is replying to the "ping" (the instruction to execute it)

The file with the system is [here](https://github.com/a801-luadev/parkour/blob/master/modes/parkour/join-system.lua), which receives the order from *#parkour0maps from [here](https://github.com/a801-luadev/parkour/blob/master/modes/maps/interface.lua#929), which receives the order from my discord bot from [here](https://github.com/a801-luadev/parkour/blob/master/bots/transformice/mapper.py#L223)

**Comment by tocuto** [comment]
Thank you for helping me test it. I've found the root cause.
